[project]
name = "zettel-app"
version = "0.3.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb==1.5.9",
    "docling>=2.71.0",
    "hdbscan==0.8.44",
    "hf-xet==1.2.0",
    "langchain-core>=1.2.7",
    "langchain-openai>=1.1.7",
    "langchain-text-splitters>=1.1.0",
    "langgraph>=0.2.0",
    "openai>=2.16.0",
    "pydantic>=2.12.5",
    "pytest>=9.0.2",
    "python-dotenv>=1.2.1",
    "python-ulid>=3.1.0",
    "pyyaml>=6.0.3",
    "rich>=14.3.2",
    "scikit-learn>=1.8.0",
    "typer>=0.21.1",
    "typer-slim==0.21.1",
    "ulid>=1.1",
    "umap-learn==0.5.12",
    "torch>=2.10.0; sys_platform == 'win32' or sys_platform == 'linux'",
    "torchvision>=0.25.0; sys_platform == 'win32' or sys_platform == 'linux'",
    "langchain-ollama>=1.0.1",
    "litellm>=1.95.0",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]


[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

