"""Compare extractor runs on the human gold set, pairwise and item by item (#181).

Each run is a key regenerated by `scripts/probe_prompt1_variant.py`: same 120 gold items,
same sampling strata and population, the verdicts of one extractor configuration. This
script answers the questions a model choice depends on:

  * **Per run** -- corpus-weighted precision, recall and F1 (with the inclusion weights
    frozen in the key), and raw precision/recall per source, so one document cannot hide
    behind the aggregate.
  * **Per pair** -- how often the two runs agree on the verdict, which items flipped and in
    which direction, crossed with the human label, and an exact paired test on item
    correctness. Two runs of one configuration make the pair a noise floor; two
    configurations make it a model or temperature effect.

The paired test is McNemar's, exact: of the items exactly one run gets right, is the split
further from even than chance allows? It uses only the discordant items, so the many items
both runs get right, or both get wrong, carry no weight -- which is what makes it the
right test for "did switching change how many chunks are judged correctly".

Offline and deterministic: reads JSON, calls no LLM, writes only `--out`.

Usage:
    .venv/Scripts/python.exe scripts/compare_gold_runs.py \\
        --run gpt4omini=evals/gold/extracao-GABARITO-gpt4omini-atual.json \\
        --run gemini-t01-a=evals/gold/extracao-GABARITO-gemini-t01-a.json \\
        --pair gpt4omini:gemini-t01-a
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

# Run from a clone without installing the package (mirrors scripts/ precedent).
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

DEFAULT_LABELS = Path("evals/gold/extracao-rotulos.json")


# -- Pure pieces ---------------------------------------------------------


def human_verdicts(labels_payload: dict[str, Any]) -> dict[str, str]:
    """item_id -> keep | discard. `?` is excluded: it is neither right nor wrong."""
    return {
        lab["item_id"]: lab["human_verdict"]
        for lab in labels_payload["labels"]
        if lab["human_verdict"] in ("keep", "discard")
    }


def correctness(items: list[Any], human: dict[str, str]) -> dict[str, bool]:
    """item_id -> whether this run's verdict matches the human, for judged items only."""
    return {
        item.item_id: (human[item.item_id] == "keep") == (item.llm_verdict == "accepted")
        for item in items
        if item.item_id in human
    }


def paired_exact_p(only_a_right: int, only_b_right: int) -> float:
    """Two-sided exact McNemar p-value over the discordant items."""
    n = only_a_right + only_b_right
    if n == 0:
        return 1.0
    k = min(only_a_right, only_b_right)
    tail = sum(math.comb(n, i) for i in range(k + 1)) / 2**n
    return min(1.0, 2 * tail)


def inclusion_weights(items: list[Any], population: dict[str, int]) -> dict[str, float]:
    """item_id -> population / sampled for the stratum the item was drawn from."""
    sampled = Counter(item.stratum for item in items)
    return {item.item_id: population.get(item.stratum, 0) / sampled[item.stratum] for item in items}


def compare_pair(
    a_items: list[Any],
    b_items: list[Any],
    human: dict[str, str],
    weights: dict[str, float] | None = None,
) -> dict:
    a_by_id = {i.item_id: i for i in a_items}
    b_by_id = {i.item_id: i for i in b_items}
    common = sorted(set(a_by_id) & set(b_by_id))

    same_verdict = sum(1 for i in common if a_by_id[i].llm_verdict == b_by_id[i].llm_verdict)
    flips: Counter[str] = Counter()
    flipped_items: list[dict[str, str]] = []
    for item_id in common:
        before, after = a_by_id[item_id].llm_verdict, b_by_id[item_id].llm_verdict
        if before == after:
            continue
        label = human.get(item_id, "unjudgeable")
        flips[f"{before}->{after} ({label})"] += 1
        flipped_items.append({"item_id": item_id, "from": before, "to": after, "human": label})

    right_a = correctness([a_by_id[i] for i in common], human)
    right_b = correctness([b_by_id[i] for i in common], human)
    only_a = sum(1 for i in right_a if right_a[i] and not right_b[i])
    only_b = sum(1 for i in right_b if right_b[i] and not right_a[i])
    # The sample over-represents the rejection boundary (a census of contested
    # rejections, 40 of 474 accepted). A raw count of net correct items weights that
    # boundary far above its share of the corpus. Weighting each discordant item by its
    # inclusion weight estimates the same difference for the corpus.
    weighted_net = None
    if weights is not None:
        weighted_net = round(
            sum(
                weights[i] * (int(right_b[i]) - int(right_a[i]))
                for i in right_a
                if right_a[i] != right_b[i]
            ),
            2,
        )
    return {
        "n_common": len(common),
        "verdict_agreement": round(same_verdict / len(common), 4) if common else 0.0,
        "flips": dict(sorted(flips.items())),
        "flipped_items": flipped_items,
        "correct_a": sum(right_a.values()),
        "correct_b": sum(right_b.values()),
        "only_a_right": only_a,
        "only_b_right": only_b,
        "paired_exact_p": round(paired_exact_p(only_a, only_b), 4),
        "weighted_net_correct_b_minus_a": weighted_net,
    }


def per_source(items: list[Any], human: dict[str, str]) -> dict[str, dict[str, Any]]:
    """Raw confusion per source (positive = a human keeps). Sample counts, not estimates."""
    counts: defaultdict[str, Counter[str]] = defaultdict(Counter)
    for item in items:
        if item.item_id not in human:
            continue
        keep = human[item.item_id] == "keep"
        accepted = item.llm_verdict == "accepted"
        cell = {(True, True): "tp", (False, True): "fp", (True, False): "fn", (False, False): "tn"}
        counts[item.source_id][cell[(keep, accepted)]] += 1
    out = {}
    for source, c in sorted(counts.items()):
        tp, fp, fn = c["tp"], c["fp"], c["fn"]
        out[source] = {
            **{k: c[k] for k in ("tp", "fp", "fn", "tn")},
            "precision": round(tp / (tp + fp), 4) if tp + fp else None,
            "recall": round(tp / (tp + fn), 4) if tp + fn else None,
        }
    return out


def parse_named(values: list[str], sep: str) -> list[tuple[str, str]]:
    pairs = []
    for value in values:
        name, found, rest = value.partition(sep)
        if not found or not name or not rest:
            raise ValueError(f"esperado NOME{sep}VALOR, recebido {value!r}")
        pairs.append((name, rest))
    return pairs


# -- CLI -----------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("--labels", type=Path, default=DEFAULT_LABELS)
    parser.add_argument("--run", action="append", default=[], help="NOME=caminho do gabarito")
    parser.add_argument("--pair", action="append", default=[], help="NOME_A:NOME_B")
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args(argv)

    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    from zettel.evals.extraction import HumanLabel, load_key, score

    labels_payload = json.loads(args.labels.read_text(encoding="utf-8"))
    human = human_verdicts(labels_payload)
    labels = [
        HumanLabel(lab["item_id"], lab["human_verdict"], lab.get("human_category") or "")
        for lab in labels_payload["labels"]
    ]

    runs = {name: load_key(Path(path)) for name, path in parse_named(args.run, "=")}
    report: dict[str, Any] = {"runs": {}, "pairs": {}}

    print(f"{'rodada':<22}{'precisao':>10}{'recall':>9}{'F1':>8}{'rej. guardaria':>16}")
    for name, (items, population) in runs.items():
        result = score(labels, items, population)
        report["runs"][name] = {
            "precision": result.precision,
            "recall": result.recall,
            "f1": result.f1,
            "rejected_but_keep_rate": result.rejected_but_keep_rate,
            "n_items": len(items),
            "per_source": per_source(items, human),
        }
        print(
            f"{name:<22}{result.precision:>10.1%}{result.recall:>9.1%}{result.f1:>8.1%}"
            f"{result.rejected_but_keep_rate:>16.1%}"
        )

    print("\nprecisao / recall por fonte (contagem crua da amostra):")
    sources = sorted({s for r in report["runs"].values() for s in r["per_source"]})
    for source in sources:
        cells = []
        for name in runs:
            ps = report["runs"][name]["per_source"].get(source, {})
            p, r = ps.get("precision"), ps.get("recall")
            fmt = lambda v: "  -  " if v is None else f"{v:.0%}"  # noqa: E731
            cells.append(f"{name}: {fmt(p)}/{fmt(r)}")
        print(f"  {source[:30]:<32}" + "   ".join(cells))

    for a_name, b_name in parse_named(args.pair, ":"):
        a_items, a_population = runs[a_name]
        pair = compare_pair(
            a_items, runs[b_name][0], human, inclusion_weights(a_items, a_population)
        )
        report["pairs"][f"{a_name}:{b_name}"] = pair
        print(f"\npar {a_name} x {b_name}: {pair['n_common']} itens em comum")
        print(f"  mesmo veredito: {pair['verdict_agreement']:.1%}")
        print(
            f"  acertos: {a_name}={pair['correct_a']}  {b_name}={pair['correct_b']}  | "
            f"so {a_name} acerta: {pair['only_a_right']}  so {b_name} acerta: "
            f"{pair['only_b_right']}  | McNemar exato p={pair['paired_exact_p']}"
        )
        print(
            f"  acertos liquidos ponderados pelo corpus ({b_name} - {a_name}): "
            f"{pair['weighted_net_correct_b_minus_a']:+.1f} chunks"
        )
        for flip, n in pair["flips"].items():
            print(f"    {flip}: {n}")

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(
            json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
